LuxuryHome/Areas/Admin/Controllers/PropertyManagerController.cs
using LuxuryHome.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace LuxuryHome.Areas.Admin.Controllers
{
    public class PropertyManagerController : Controller
    {
        PPCDBEntities1 model = new PPCDBEntities1();
        // GET: Admin/Admin
        public ActionResult Index()
        {
            var property = model.Properties.ToList();
            return View(property);
        }

        public ActionResult Create()
        {
            PoPularData();
            return View();
        }

        public void PoPularData(object propertyTypeSelected = null, object districtSelected = null, object propertyStatusSelectec = null)
        {
            ViewBag.Property_Type_ID = new SelectList(model.Property_Type.ToList(), "ID", "Property_Type_Name", propertyTypeSelected);
            ViewBag.District_ID = new SelectList(model.Districts.ToList(), "ID", "District_Name", districtSelected);
            ViewBag.Property_Status_ID = new SelectList(model.Property_Status.ToList(), "ID", "Property_Status_Name", propertyStatusSelectec);
        }
        [HttpPost]
        public ActionResult Create([Bind(Include = "Property_Name,Property_Type_ID,Description,District_ID,Address" +
            ",Area,Bed_Room,Bath_Room,Price,Installment_Rate,Avatar,Album,Property_Status_ID")]
        Property property, List<HttpPostedFileBase> files, HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                string album = "";
                // var file = Request.Files["files"];
                Random random = new Random();
                //Up Album
                if (files != null)
                {
                    using (var scope = new TransactionScope())
                    {
                        foreach (var imageFile in files)
                        {
                            if (imageFile != null)
                            {
                                var fileName = random.Next(1, 99999).ToString() + Path.GetFileName(imageFile.FileName);
                                var physicalPath = Path.Combine(Server.MapPath("~/Images"), fileName);

                                // The files are not actually saved in this demo
                                imageFile.SaveAs(physicalPath);
                                album += album.Length > 0 ? ";" + fileName : fileName;
                            }
                        }
                    }
                    property.Album = album;
                    //Avatar
                    if (file != null)
                    {
                        var avatar = random.Next(1, 99999).ToString() + Path.GetFileName(file.FileName);
                        var physicPath = Path.Combine(Server.MapPath("~/Images"), avatar);
                        file.SaveAs(physicPath);
                        property.Avatar = avatar;
                    }

                }


                model.Properties.Add(property);
                model.SaveChanges();
                PopularMessage(true);
            }
            else
                PopularMessage(false);
            return Redirect("Index");
        }



        public void PopularMessage(bool success)
        {
            if (success)
                Session["success"] = "Successfull";
            else
                Session["success"] = "Fail";
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var property = model.Properties.FirstOrDefault(x => x.ID == id);
            PoPularData(property.Property_Type_ID, property.District_ID, property.Property_Status_ID);
            return View(property);
        }
        [HttpPost]
        public ActionResult Edit(Property pp, int id, List<HttpPostedFileBase> files, HttpPostedFileBase file)
        {
            var Property = model.Properties.ToList();
            try
            {
                var property = model.Properties.Select(p => p).Where(p => p.ID == id).FirstOrDefault();
                PoPularData(property.Property_Type_ID, property.Property_Status_ID);
                property.Property_Name = pp.Property_Name;
                property.Property_Type_ID = pp.Property_Type_ID;
                property.Description = pp.Description;
                property.District_ID = pp.District_ID;
                property.Address = pp.Address;
                property.Area = pp.Area;             
                property.Bath_Room = pp.Bath_Room;
                property.Bed_Room = pp.Bed_Room;
                property.Price = pp.Price;
                property.Installment_Rate = pp.Installment_Rate;
                property.Property_Status_ID = pp.Property_Status_ID;                            
                string album = "";
                //var file = Request.Files["files"];

                Random random = new Random();
                //Up Album
                if (files != null)
                {
                    using (var scrope = new TransactionScope())
                    {
                        foreach (var imageFile in files)
                        {
                            if (imageFile != null)
                            {
                                var fileName = random.Next(1, 99999).ToString() + Path.GetFileName(imageFile.FileName);
                                var physicalPath = Path.Combine(Server.MapPath("~/Images"), fileName);

                                // The files are not actually saved in this demo
                                imageFile.SaveAs(physicalPath);
                                album += album.Length > 0 ? ";" + fileName : fileName;
                            }
                        }
                    }
                    property.Album = album;
                    //Avatar
                    if (file != null)
                    {

                        var avatar = random.Next(1, 99999).ToString() + Path.GetFileName(file.FileName);
                        var physicPath = Path.Combine(Server.MapPath("~/Images"), avatar);
                        file.SaveAs(physicPath);
                        property.Avatar = avatar;
                    }
                }
                model.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(Property);
            }
        }



        [HttpGet]
        public ActionResult Delete(int id)
        {
            var property = model.Properties.Select(p => p).Where(p => p.ID == id).FirstOrDefault();
            return View(property);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var property = model.Properties.Select(p => p).Where(p => p.ID == id).FirstOrDefault();
                if (property != null)
                {
                    model.Properties.Remove(property);
                    model.SaveChanges();
                }
                return RedirectToAction("Index");

            }
            catch { return View(); }
        }
        [HttpPost] 
        public string deleteImage(string imageName, int id)
        {
            string fullPath = Request.MapPath("~/Images" + imageName);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            var property = model.Properties.FirstOrDefault(x => x.ID == id);
            var album = property.Album.Split(';');
            album = album.Where(w => w != imageName).ToArray();
            property.Album = string.Join(";", album);

            model.Entry(property).State = System.Data.Entity.EntityState.Modified;
            model.SaveChanges();
            return property.Album;

        }
        public JsonResult GetDistrictByCityId(int id)
        {
            // Disable proxy creation
            model.Configuration.ProxyCreationEnabled = false;
            var listDistrict = model.Districts.Where(x => x.City_ID == id).ToList();
            return Json(listDistrict, JsonRequestBehavior.AllowGet);
        }
    }
}

LuxuryHome/Areas/Admin/Views/PropertyManager/Create.cshtml
@model LuxuryHome.Models.Property

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@Html.ValidationSummary(excludePropertyErrors: true)
@using (Html.BeginForm("Create", "PropertyManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 align="center">Create Property</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Property_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Property_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Property_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_Type_ID, "Property_Type_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Property_Type_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Property_Type_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.District_ID, "District_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("District_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.District_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bed_Room, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bed_Room, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bed_Room, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bath_Room, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bath_Room, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bath_Room, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Installment_Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Installment_Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Installment_Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" />
                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input multiple type="file" name="files" />
                @Html.ValidationMessageFor(model => model.Album, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_Status_ID, "Property_Status_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Property_Status_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Property_Status_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script>
    function readIMG(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(input).next()
                    .attr('src', e.target.result)
                    .width(600)
                    .height(400);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

LuxuryHome/Areas/Admin/Views/PropertyManager/Delete.cshtml
@model LuxuryHome.Models.Property

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<h3 align="center">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Property_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bed_Room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bed_Room)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bath_Room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bath_Room)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Installment_Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Installment_Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.District.District_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.District.District_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Status.Property_Status_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Status.Property_Status_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Type.Property_Type_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Type.Property_Type_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LuxuryHome/Areas/Admin/Views/PropertyManager/Edit.cshtml
@model LuxuryHome.Models.Property

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@Html.ValidationSummary(excludePropertyErrors: true)
@using (Html.BeginForm("Edit", "PropertyManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 align="center">Edit Property</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Property_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property_Code, new { htmlAttributes = new { @class = "form-control" } })
                 @Html.ValidationMessageFor(model => model.Property_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Property_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_Type_ID, "Property_Type_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Property_Type_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Property_Type_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.District_ID, "District_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("District_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.District_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bed_Room, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bed_Room, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bed_Room, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bath_Room, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bath_Room, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bath_Room, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Installment_Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Installment_Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Installment_Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (!String.IsNullOrEmpty(Model.Avatar) && Model.Avatar != "")
                {<img src="@(Url.Content("~/Images/" + Model.Avatar))" width="80" />}
                <input name="file" type="file" multiple />
                @Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="files" type="file" multiple />
                @Html.EditorFor(model => model.Album, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @if (!String.IsNullOrEmpty(Model.Album) && Model.Album != "")
                {
                    foreach (var image in Model.Album.Split(';'))
                    {
                        if (!String.IsNullOrEmpty(image) || image != "")
                        {
                            int i = 0;
                            <span id="image-@(i)">
                                <img src="@(Url.Content("~/Images/" + image))" width="80" />
                                <button type="button" class="btn btn-danger" onclick="@("deleteImage(\"" + image + "\"," + Model.ID + "," + i + ");")">Delete</button>
                            </span>
                            i++;
                        }
                    }

                }
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Property_Status_ID, "Property_Status_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Property_Status_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Property_Status_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}
<script>
    function deleteImage(image, id, i) {
        event.preventDefault();
        $.post("/Admin/PropertyManager/deleteImage",         
            {
                imageName: image,
                id: id
            },
            function (data, status) {
                $("#album").val(data);
                $("#image-" + i).hide();
            });
    }
</script>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LuxuryHome/Areas/Admin/Views/PropertyManager/Index.cshtml
@model IEnumerable<LuxuryHome.Models.Property>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<p>
    <br />
    @Html.ActionLink("Create New", "Create", null, new { @class = " btn btn-success" })

    <!--thongbao-->
    @if (Session["success"] != null)
    {
        <div class="alert alert-success alert-dismissible" role="alert">

            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Well done!</strong> @Session["success"]
        </div>
    }
</p>

<div class="card-body">
    <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Property_Code</th>
                <th>Property_Name</th>
                <th>Property_Status_Name</th>
                <th>Price</th>
                <th>Avatar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Property_Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Property_Name)
                    </td>
                    <td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                      <img src="~/Images/@item.Avatar" width="100px" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Property_Status.ID)
                    </td>
                    <td>

                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = " btn btn-warning" }) |                      
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = " btn btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
       
    </table>
</div>